name: fluttersnips
description: A comprehensive component library for Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # a
  awesome_snackbar_content: ^0.1.3

  # c
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.2
  
  # f
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter_inappwebview: ^5.7.2+3
  flutter_dotenv: ^5.1.0
  
  # g
  glassy: ^0.0.6
  google_sign_in: ^6.1.4
  google_fonts: ^4.0.4
  
  # p
  provider: ^6.0.5
  
  # r
  random_avatar: ^0.0.8
  rive: ^0.11.3

  # s
  selectable_code_view: ^0.0.1
  
  # u
  url_launcher: ^6.1.11
  
  flutter_glow: ^0.3.0
  font_awesome_flutter: ^10.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - images/
